[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
vero = "3KX1asvGaP1h2UHaxbHoT4WA5Gf6Ex524zYwgwB2Cn3V"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
